### ISSUE TITLE
No puedo importar módulos nativos de Node.js en el .spec.ts para las pruebas.

### ISSUE THREAD

**Issue by adahi-oval** [ULL-ESIT-INF-DSI-2324/ull-esit-inf-dsi-23-24-prct10-fs-proc-sockets-magic-app-adahiOval#2]
@esegredo Estaba desarrollando las pruebas para la práctica, usando el ejemplo de los apuntes para pruebas sobre sockets con mocha y chai y en el ejemplo se importa EventEmitter de 'events', pero al hacer eso no reconoce el módulo dentro del spec ni ese ni ningún otro módulo nativo de Node.js como 'net' por ejemplo.

**Comment by esegredo** [comment]
Hola, buenas.

¿Has instalado @types/node?

Saludos.

**Comment by adahi-oval** [comment]
sí, lo tenía instalado pero parece que el problema era con la versión porque al reinstalarlo se solucionó de cara a la práctica 11
